#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/darioedelstein/Development/Flutter SDK/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/darioedelstein/Documents/Kenility/TruVideo/Wolverine/truvideopro-flutter-code/flutter_twilio_voice"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/darioedelstein/Development/Flutter SDK/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.0.4"
export "FLUTTER_BUILD_NUMBER=0.0.4"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
